/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moya_javaproject;

/**
 *
 * @author 2ndyrGroupA
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static moya_javaproject.login.USERNAME;
//import static moya_javaproject.login.COUNT;
public class landing extends javax.swing.JFrame {

    /**
     * Creates new form landing
     */
    public landing() {
        initComponents();
        nameuser.setText(USERNAME);
        
       this.setLocationRelativeTo(null); //center to display
    }
   
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        manageGroups = new javax.swing.JToggleButton();
        manageUsers = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        manageProduct = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dashboard = new javax.swing.JToggleButton();
        purchase = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        hover1 = new javax.swing.JPanel();
        purchases = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        hover2 = new javax.swing.JPanel();
        totalvitamins = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        hover4 = new javax.swing.JPanel();
        allprofitp = new java.awt.Label();
        allprofit = new javax.swing.JLabel();
        hover5 = new javax.swing.JPanel();
        zestod = new java.awt.Label();
        zesto = new javax.swing.JLabel();
        profitz = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hover6 = new javax.swing.JPanel();
        yakult = new java.awt.Label();
        yakults = new javax.swing.JLabel();
        yakultp = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hover7 = new javax.swing.JPanel();
        enervon = new java.awt.Label();
        enervons = new javax.swing.JLabel();
        enervonp = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        hover8 = new javax.swing.JPanel();
        pederin = new java.awt.Label();
        pederins = new javax.swing.JLabel();
        pederinp = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        hover3 = new javax.swing.JPanel();
        drinks2 = new java.awt.Label();
        drinks = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameuser = new javax.swing.JLabel();
        logoutb = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/title.PNG"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        manageGroups.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        manageGroups.setText("Manage Groups");
        manageGroups.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        manageGroups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageGroupsMouseClicked(evt);
            }
        });
        manageGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageGroupsActionPerformed(evt);
            }
        });

        manageUsers.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        manageUsers.setText("Manage Users");
        manageUsers.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        manageUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUsersMouseClicked(evt);
            }
        });
        manageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/plus.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/plus.png"))); // NOI18N

        manageProduct.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        manageProduct.setText("Manage Products");
        manageProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        manageProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageProductMouseClicked(evt);
            }
        });
        manageProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/plus.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/plus.png"))); // NOI18N

        dashboard.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });

        purchase.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        purchase.setText("Manage Order");
        purchase.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        purchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseMouseClicked(evt);
            }
        });
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(49, 49, 49)
                        .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(manageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(manageGroups, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(manageProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(52, 52, 52))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manageProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel11))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(manageGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(668, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/lastwel.png"))); // NOI18N

        hover1.setBackground(new java.awt.Color(204, 204, 204));
        hover1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 255, 255), null, null));
        hover1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover1MouseExited(evt);
            }
        });

        purchases.setBackground(new java.awt.Color(255, 255, 255));
        purchases.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        purchases.setForeground(new java.awt.Color(255, 0, 0));

        label3.setBackground(null);
        label3.setFont(new java.awt.Font("Euphemia", 1, 24)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 153, 0));
        label3.setText("Total Stocks");
        label3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hover1Layout = new javax.swing.GroupLayout(hover1);
        hover1.setLayout(hover1Layout);
        hover1Layout.setHorizontalGroup(
            hover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover1Layout.createSequentialGroup()
                .addGroup(hover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hover1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(purchases, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hover1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        hover1Layout.setVerticalGroup(
            hover1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(purchases, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hover2.setBackground(new java.awt.Color(204, 255, 204));
        hover2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        hover2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover2MouseExited(evt);
            }
        });

        totalvitamins.setBackground(new java.awt.Color(255, 255, 255));
        totalvitamins.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalvitamins.setForeground(new java.awt.Color(51, 204, 255));

        label2.setFont(new java.awt.Font("Euphemia", 1, 24)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 153, 0));
        label2.setText("Total Vitamins");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hover2Layout = new javax.swing.GroupLayout(hover2);
        hover2.setLayout(hover2Layout);
        hover2Layout.setHorizontalGroup(
            hover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalvitamins, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        hover2Layout.setVerticalGroup(
            hover2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(totalvitamins, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        hover4.setBackground(new java.awt.Color(204, 255, 204));
        hover4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover4MouseExited(evt);
            }
        });

        allprofitp.setFont(new java.awt.Font("Euphemia", 1, 24)); // NOI18N
        allprofitp.setForeground(new java.awt.Color(255, 153, 0));
        allprofitp.setText("All Profit");
        allprofitp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allprofitpMouseClicked(evt);
            }
        });

        allprofit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        allprofit.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout hover4Layout = new javax.swing.GroupLayout(hover4);
        hover4.setLayout(hover4Layout);
        hover4Layout.setHorizontalGroup(
            hover4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(hover4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(allprofitp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allprofit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );
        hover4Layout.setVerticalGroup(
            hover4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover4Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(allprofit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allprofitp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hover5.setBackground(new java.awt.Color(204, 255, 204));
        hover5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover5MouseExited(evt);
            }
        });

        zestod.setFont(new java.awt.Font("Euphemia", 1, 24)); // NOI18N
        zestod.setForeground(new java.awt.Color(255, 153, 0));
        zestod.setText("Zesto");
        zestod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zestodMouseClicked(evt);
            }
        });

        zesto.setBackground(new java.awt.Color(255, 255, 255));
        zesto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        zesto.setForeground(new java.awt.Color(255, 0, 0));

        profitz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel3.setText("Stocks:");

        jLabel4.setText("Profit:");

        javax.swing.GroupLayout hover5Layout = new javax.swing.GroupLayout(hover5);
        hover5.setLayout(hover5Layout);
        hover5Layout.setHorizontalGroup(
            hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hover5Layout.createSequentialGroup()
                        .addGroup(hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(zestod, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(hover5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(zesto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(profitz, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(hover5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(49, 49, 49))))
        );
        hover5Layout.setVerticalGroup(
            hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hover5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(zesto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profitz, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zestod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hover6.setBackground(new java.awt.Color(204, 204, 204));
        hover6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover6MouseExited(evt);
            }
        });

        yakult.setFont(new java.awt.Font("Euphemia", 1, 24)); // NOI18N
        yakult.setForeground(new java.awt.Color(255, 153, 0));
        yakult.setText("Yakult");
        yakult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yakultMouseClicked(evt);
            }
        });

        yakults.setBackground(new java.awt.Color(255, 255, 255));
        yakults.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        yakults.setForeground(new java.awt.Color(255, 0, 0));

        yakultp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel5.setText("Stocks:");

        jLabel12.setText("Profit:");

        javax.swing.GroupLayout hover6Layout = new javax.swing.GroupLayout(hover6);
        hover6.setLayout(hover6Layout);
        hover6Layout.setHorizontalGroup(
            hover6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hover6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hover6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(49, 49, 49))
                    .addGroup(hover6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(yakults, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(yakultp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yakult, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        hover6Layout.setVerticalGroup(
            hover6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(hover6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hover6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yakults, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yakultp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yakult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hover7.setBackground(new java.awt.Color(204, 255, 204));
        hover7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover7MouseExited(evt);
            }
        });

        enervon.setFont(new java.awt.Font("Euphemia", 1, 24)); // NOI18N
        enervon.setForeground(new java.awt.Color(255, 153, 0));
        enervon.setText("Enervon");
        enervon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enervonMouseClicked(evt);
            }
        });

        enervons.setBackground(new java.awt.Color(255, 255, 255));
        enervons.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        enervons.setForeground(new java.awt.Color(255, 0, 0));

        enervonp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel14.setText("Stocks:");

        jLabel15.setText("Profit:");

        javax.swing.GroupLayout hover7Layout = new javax.swing.GroupLayout(hover7);
        hover7.setLayout(hover7Layout);
        hover7Layout.setHorizontalGroup(
            hover7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(hover7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hover7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(49, 49, 49))
                    .addGroup(hover7Layout.createSequentialGroup()
                        .addGroup(hover7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hover7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(enervons, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(enervonp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hover7Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(enervon, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        hover7Layout.setVerticalGroup(
            hover7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(hover7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hover7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enervons, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enervonp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enervon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hover8.setBackground(new java.awt.Color(204, 204, 204));
        hover8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hover8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover8MouseExited(evt);
            }
        });

        pederin.setFont(new java.awt.Font("Euphemia", 1, 24)); // NOI18N
        pederin.setForeground(new java.awt.Color(255, 153, 0));
        pederin.setText("Periden-C");
        pederin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pederinMouseClicked(evt);
            }
        });

        pederins.setBackground(new java.awt.Color(255, 255, 255));
        pederins.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pederins.setForeground(new java.awt.Color(255, 0, 0));

        pederinp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel16.setText("Stocks:");

        jLabel17.setText("Profit:");

        javax.swing.GroupLayout hover8Layout = new javax.swing.GroupLayout(hover8);
        hover8.setLayout(hover8Layout);
        hover8Layout.setHorizontalGroup(
            hover8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(hover8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hover8Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(49, 49, 49))
                    .addGroup(hover8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(hover8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pederin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(hover8Layout.createSequentialGroup()
                                .addComponent(pederins, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pederinp, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        hover8Layout.setVerticalGroup(
            hover8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(hover8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(hover8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pederins, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pederinp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pederin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hover3.setBackground(new java.awt.Color(204, 204, 204));
        hover3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));
        hover3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hover3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hover3MouseExited(evt);
            }
        });

        drinks2.setFont(new java.awt.Font("Euphemia", 1, 24)); // NOI18N
        drinks2.setForeground(new java.awt.Color(255, 153, 0));
        drinks2.setText("Total Drinks");
        drinks2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drinks2MouseClicked(evt);
            }
        });

        drinks.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        drinks.setForeground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout hover3Layout = new javax.swing.GroupLayout(hover3);
        hover3.setLayout(hover3Layout);
        hover3Layout.setHorizontalGroup(
            hover3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drinks2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hover3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drinks, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        hover3Layout.setVerticalGroup(
            hover3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hover3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(drinks, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drinks2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/vita2.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/vita.jpg"))); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/vita3.jpg"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/vita.jpg"))); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/y2.jpg"))); // NOI18N
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/z.jpg"))); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/p.jpg"))); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hover5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hover6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hover1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hover2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hover7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hover8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hover3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hover4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel13)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel24))))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hover2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hover1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hover3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hover4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hover5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hover6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hover7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hover8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(670, Short.MAX_VALUE))))
        );

        jLabel6.setFont(new java.awt.Font("Ink Free", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 51));
        jLabel6.setText("MANAGE YOUR DATA PRIVACY AND SECURITY");

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/administrator.png"))); // NOI18N

        nameuser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nameuser.setForeground(new java.awt.Color(0, 51, 51));

        logoutb.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        logoutb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/logout2.png"))); // NOI18N
        logoutb.setText("Logout");
        logoutb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addComponent(nameuser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(logoutb))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameuser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutb, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(9, 9, 9)))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUsersMouseClicked
        dispose();
        ManageUsers open = new  ManageUsers();
        open.setVisible(true);
    }//GEN-LAST:event_manageUsersMouseClicked

    private void manageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageUsersActionPerformed

    private void manageProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageProductMouseClicked
        dispose();
        ManageProduct open = new  ManageProduct();
        open.setVisible(true);
    }//GEN-LAST:event_manageProductMouseClicked

    private void manageProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageProductActionPerformed

    private void logoutbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbMouseClicked
           dispose();
           login welcome = new login();
           welcome.setVisible(true);  
       
    }//GEN-LAST:event_logoutbMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       landing welcome = new landing();
          welcome.setVisible(true); 
           dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        dispose();
        landing welcome = new landing();
        welcome.setVisible(true); 
    }//GEN-LAST:event_dashboardMouseClicked

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    private void zestodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zestodMouseClicked
           try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
           Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)  
           ResultSet datas = stmt.executeQuery("select * from `products`");
           datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products` WHERE product_title ='Zesto'");
           datas.next();
           int count = datas.getInt(1);
           ResultSet order = stmt.executeQuery("select * from `productorder`");
           order = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE product_title ='Zesto'");//sum of the ordered p
           order.next();
           int count3 = order.getInt(1);
           zesto.setText(String.valueOf(count-count3));//getting the final stocks
           
           
           //getting the profit of every product
           ResultSet data2 = stmt.executeQuery("select * from `products`");
           data2 = stmt.executeQuery("Select (selling_price-buying_price)*SUM(`in_stock`)from `products` WHERE product_title ='Zesto'");
           data2.next();
           int count2 = data2.getInt(1);
           profitz.setText(String.valueOf(count2));
           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        
    }           

    }//GEN-LAST:event_zestodMouseClicked

    
    private void label3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label3MouseClicked
      
    
        try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
           Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)  
           ResultSet datas = stmt.executeQuery("select * from `products`");
           datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products`");
           datas.next();
           int ptotal = datas.getInt(1);
            //getting the final stocks of the drinks
           ResultSet drinks = stmt.executeQuery("select * from `productorder`");
           drinks = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE category ='Drinks'");//sum of the ordered product
           drinks.next();
           int drinkst = drinks.getInt(1);
           
            //getting the final stocks of the vitamins
           ResultSet vitamins = stmt.executeQuery("select * from `productorder`");
           vitamins = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE category ='Vitamins'");//sum of the ordered product
           vitamins.next();
           int vitaminst = vitamins.getInt(1);
           purchases.setText(String.valueOf(ptotal-(drinkst+vitaminst)));//getting the final total of stocks  both drinks and vitamins


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
    }//GEN-LAST:event_label3MouseClicked

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked
        try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
           Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)  
           ResultSet datas = stmt.executeQuery("select * from `products`");
           datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products` WHERE category ='Vitamins'");
           datas.next();
           int count = datas.getInt(1);
           //getting the final stock of the vitamins
           ResultSet order = stmt.executeQuery("select * from `productorder`");
           order = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE category ='Vitamins'");//sum of the ordered p
           order.next();
           int count3 = order.getInt(1);
           totalvitamins.setText(String.valueOf(count-count3));


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        
    }           

    }//GEN-LAST:event_label2MouseClicked

    private void manageGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageGroupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageGroupsActionPerformed

    private void manageGroupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageGroupsMouseClicked
        dispose();
        ManageGroups open = new ManageGroups();
        open.setVisible(true);
    }//GEN-LAST:event_manageGroupsMouseClicked

    private void purchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseMouseClicked
        dispose();
        ManageOrder welcome = new ManageOrder();
        welcome.setVisible(true);
    }//GEN-LAST:event_purchaseMouseClicked
   
    
    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseActionPerformed

    private void allprofitpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allprofitpMouseClicked
         try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
           Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)  
           //for zesto
           ResultSet data2 = stmt.executeQuery("select * from `products`");
           data2 = stmt.executeQuery("Select (selling_price-buying_price)*SUM(`in_stock`)from `products` WHERE product_title ='Zesto'");
           data2.next();
           int zesto = data2.getInt(1);
           //for yakult
           //int count = datas.getInt(1);
           //yakults.setText(String.valueOf(count));
           ResultSet data3 = stmt.executeQuery("select * from `products`");
           data3 = stmt.executeQuery("Select (selling_price-buying_price)*SUM(`in_stock`)from `products` WHERE product_title ='Yakult'");
           data3.next();
           int yakult = data3.getInt(1);
         
          // profitz.setText(String.valueOf(count2));
          //for enervon
           ResultSet data4 = stmt.executeQuery("select * from `products`");
           data4 = stmt.executeQuery("Select (selling_price-buying_price)*SUM(`in_stock`)from `products` WHERE product_title ='Enervon'");
           data4.next();
           int enervon = data4.getInt(1);
           //enervonp.setText(String.valueOf(count2));
           ResultSet data1 = stmt.executeQuery("select * from `products`");
           data1 = stmt.executeQuery("Select (selling_price-buying_price)*SUM(`in_stock`)from `products` WHERE product_title ='Peridin-C'");
           data1.next();
           int peridin = data1.getInt(1);
           allprofit.setText(String.valueOf(zesto+yakult+peridin+enervon));
           
           
          
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        
    }       
    }//GEN-LAST:event_allprofitpMouseClicked

    private void yakultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yakultMouseClicked
         try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
           Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)  
           ResultSet datas = stmt.executeQuery("select * from `products`");
           datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products` WHERE product_title ='Yakult'");
           datas.next();
           int count = datas.getInt(1);
           ResultSet order = stmt.executeQuery("select * from `productorder`");
           order = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE product_title ='Yakult'");//sum of the ordered p
           order.next();
           int count3 = order.getInt(1);
           yakults.setText(String.valueOf(count-count3));//get the final stock minus by the order
           
           //getting the profit
           ResultSet data2 = stmt.executeQuery("select * from `products`");
           data2 = stmt.executeQuery("Select (selling_price-buying_price)*SUM(`in_stock`)from `products` WHERE product_title ='Yakult'");
           data2.next();
           int count2 = data2.getInt(1);
           yakultp.setText(String.valueOf(count2));
           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        
    }           
    }//GEN-LAST:event_yakultMouseClicked

    private void enervonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enervonMouseClicked
         try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
           Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)  
           ResultSet datas = stmt.executeQuery("select * from `products`");
           datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products` WHERE product_title ='Enervon'");
           datas.next();
           int count = datas.getInt(1);
           ResultSet order = stmt.executeQuery("select * from `productorder`");
           order = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE product_title ='Enervon'");
           order.next();
           int count3 = order.getInt(1);
           enervons.setText(String.valueOf(count-count3));//getting the final stocks
           
           //getting the profit
           ResultSet data2 = stmt.executeQuery("select * from `products`");
           data2 = stmt.executeQuery("Select (selling_price-buying_price)*SUM(`in_stock`)from `products` WHERE product_title ='Enervon'");
           data2.next();
           int count2 = data2.getInt(1);
           enervonp.setText(String.valueOf(count2));
           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
    }//GEN-LAST:event_enervonMouseClicked

    private void pederinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pederinMouseClicked
        try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
           Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)  
           ResultSet datas = stmt.executeQuery("select * from `products`");
           datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products` WHERE product_title ='Peridin-C'");//sum of  the stock in product t
           datas.next();
           int count = datas.getInt(1);
           ResultSet order = stmt.executeQuery("select * from `productorder`");
           order = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE product_title ='Peridin-C'");//sum of the ordered p
           order.next();
           int count3 = order.getInt(1);
           pederins.setText(String.valueOf(count-count3));//getting the final stocks minus with the orders
           
           //getting the profit
           ResultSet data2 = stmt.executeQuery("select * from `products`");
           data2 = stmt.executeQuery("Select (selling_price-buying_price)*SUM(`in_stock`)from `products` WHERE product_title ='Peridin-C'");
           data2.next();
           int count2 = data2.getInt(1);
           pederinp.setText(String.valueOf(count2));
           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
    }//GEN-LAST:event_pederinMouseClicked

    private void hover8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover8MouseClicked
       
    }//GEN-LAST:event_hover8MouseClicked

    private void drinks2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drinks2MouseClicked
       try {
           Class.forName("com.mysql.jdbc.Driver"); //load the driver
           Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
           Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)  
           ResultSet datas = stmt.executeQuery("select * from `products`");
           datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products` WHERE category ='Drinks'");//total stocks of drinks from products
           datas.next();
           int count = datas.getInt(1);
           //getting the final stocks of the drinks
           ResultSet order = stmt.executeQuery("select * from `productorder`");
           order = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE category ='Drinks'");//sum of the ordered product
           order.next();
           int count3 = order.getInt(1);
           drinks.setText(String.valueOf(count-count3));//final stock  of drinks minus the orders


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        
    }        
    }//GEN-LAST:event_drinks2MouseClicked
     public void setColor(JPanel p){
        p.setBackground(new Color(204,255,204));
    }
     public void resetColor(JPanel p1){
        p1.setBackground(new Color(204,204,204));
    }
    
    private void hover1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover1MouseEntered
            setColor(hover1);
    }//GEN-LAST:event_hover1MouseEntered

    private void hover1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover1MouseExited
            resetColor(hover1);
    }//GEN-LAST:event_hover1MouseExited

    private void hover2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover2MouseEntered
                 resetColor(hover2);
    }//GEN-LAST:event_hover2MouseEntered

    private void hover2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover2MouseExited
                   setColor(hover2);
    }//GEN-LAST:event_hover2MouseExited

    private void hover3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover3MouseEntered
          setColor(hover3);
    }//GEN-LAST:event_hover3MouseEntered

    private void hover3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover3MouseExited
        resetColor(hover3);
    }//GEN-LAST:event_hover3MouseExited

    private void hover4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover4MouseEntered
          resetColor(hover4);
    }//GEN-LAST:event_hover4MouseEntered

    private void hover4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover4MouseExited
         setColor(hover4);
    }//GEN-LAST:event_hover4MouseExited

    private void hover5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover5MouseEntered
         resetColor(hover5);
    }//GEN-LAST:event_hover5MouseEntered

    private void hover5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover5MouseExited
        setColor(hover5);
    }//GEN-LAST:event_hover5MouseExited

    private void hover6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover6MouseEntered
         setColor(hover6);
    }//GEN-LAST:event_hover6MouseEntered

    private void hover6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover6MouseExited
          resetColor(hover6);
    }//GEN-LAST:event_hover6MouseExited

    private void hover7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover7MouseEntered
        resetColor(hover7);
    }//GEN-LAST:event_hover7MouseEntered

    private void hover7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover7MouseExited
        setColor(hover7);
    }//GEN-LAST:event_hover7MouseExited

    private void hover8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover8MouseEntered
       setColor(hover8);
    }//GEN-LAST:event_hover8MouseEntered

    private void hover8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hover8MouseExited
        resetColor(hover8);
    }//GEN-LAST:event_hover8MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(landing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new landing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel allprofit;
    private java.awt.Label allprofitp;
    private javax.swing.JToggleButton dashboard;
    private javax.swing.JLabel drinks;
    private java.awt.Label drinks2;
    private java.awt.Label enervon;
    private javax.swing.JLabel enervonp;
    private javax.swing.JLabel enervons;
    private javax.swing.JPanel hover1;
    private javax.swing.JPanel hover2;
    private javax.swing.JPanel hover3;
    private javax.swing.JPanel hover4;
    private javax.swing.JPanel hover5;
    private javax.swing.JPanel hover6;
    private javax.swing.JPanel hover7;
    private javax.swing.JPanel hover8;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel logoutb;
    private javax.swing.JToggleButton manageGroups;
    private javax.swing.JToggleButton manageProduct;
    private javax.swing.JToggleButton manageUsers;
    private javax.swing.JLabel nameuser;
    private java.awt.Label pederin;
    private javax.swing.JLabel pederinp;
    private javax.swing.JLabel pederins;
    private javax.swing.JLabel profitz;
    private javax.swing.JToggleButton purchase;
    private javax.swing.JLabel purchases;
    private javax.swing.JLabel totalvitamins;
    private java.awt.Label yakult;
    private javax.swing.JLabel yakultp;
    private javax.swing.JLabel yakults;
    private javax.swing.JLabel zesto;
    private java.awt.Label zestod;
    // End of variables declaration//GEN-END:variables
}
