/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moya_javaproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static moya_javaproject.login.USERNAME;

/**
 *
 * @author student.admin
 */
public class ManageOrder extends javax.swing.JFrame {

    /**
     * Creates new form ManageOrder
     */
    public ManageOrder() {
        initComponents();
        getData();
        nameuser2.setText(USERNAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        manageGroups = new javax.swing.JToggleButton();
        manageUsers = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        manageProduct = new javax.swing.JToggleButton();
        jLabel15 = new javax.swing.JLabel();
        dashboard = new javax.swing.JToggleButton();
        purchase = new javax.swing.JToggleButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        addo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        addorder = new javax.swing.JToggleButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        dateo = new com.toedter.calendar.JDateChooser();
        addp = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        oc = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        addprice = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        upop = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        upopi = new javax.swing.JTextField();
        updateorder = new javax.swing.JToggleButton();
        upoid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        updatedate = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        upoc = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        upprice = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        delo = new javax.swing.JTextField();
        deleteorder = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        hoverr = new javax.swing.JPanel();
        availablezesb = new java.awt.Label();
        jLabel27 = new javax.swing.JLabel();
        availableyakultb = new java.awt.Label();
        availableyakult = new javax.swing.JLabel();
        availableenervonb = new java.awt.Label();
        availableenervon = new javax.swing.JLabel();
        avalaiblepederin = new javax.swing.JLabel();
        availablepederinb = new java.awt.Label();
        availablezes = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalorder = new javax.swing.JLabel();
        order = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        logoutb = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nameuser2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel6.setBackground(new java.awt.Color(255, 153, 0));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/title.PNG"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        manageGroups.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        manageGroups.setText("Manage Groups");
        manageGroups.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        manageGroups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageGroupsMouseClicked(evt);
            }
        });
        manageGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageGroupsActionPerformed(evt);
            }
        });

        manageUsers.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        manageUsers.setText("Manage Users");
        manageUsers.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        manageUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUsersMouseClicked(evt);
            }
        });
        manageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/plus.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/plus.png"))); // NOI18N

        manageProduct.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        manageProduct.setText("Manage Products");
        manageProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        manageProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageProductMouseClicked(evt);
            }
        });
        manageProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageProductActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/plus.png"))); // NOI18N

        dashboard.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        dashboard.setText("Dashboard");
        dashboard.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardActionPerformed(evt);
            }
        });

        purchase.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        purchase.setText("Manage Order");
        purchase.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        purchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purchaseMouseClicked(evt);
            }
        });
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(manageGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manageProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel8)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel13))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(manageProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(purchase, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(manageGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel15))
        );

        jPanel10.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));

        addo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255)));
        addo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Product Title");

        addorder.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        addorder.setText("ADD");
        addorder.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        addorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addorderMouseClicked(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 102, 102));
        jTextField5.setText("                                              Add Order");
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 153, 0));
        jLabel23.setText("Date");

        dateo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 255), null, null));

        addp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255)));
        addp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 153, 0));
        jLabel24.setText("Price");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Category");

        oc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drinks", "Vitamins" }));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 153, 0));
        jLabel26.setText("Pieces");

        addprice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255)));
        addprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(oc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addo)
                            .addComponent(addp)
                            .addComponent(dateo, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(addprice))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(addorder, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addp, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addprice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addorder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );

        ordertable.setBorder(new javax.swing.border.MatteBorder(null));
        ordertable.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        ordertable.setForeground(new java.awt.Color(0, 51, 51));
        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product Title", "Category", "Pcs.", "Price", "Total", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ordertable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ordertableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ordertable);
        if (ordertable.getColumnModel().getColumnCount() > 0) {
            ordertable.getColumnModel().getColumn(0).setMinWidth(20);
            ordertable.getColumnModel().getColumn(0).setPreferredWidth(20);
            ordertable.getColumnModel().getColumn(1).setMinWidth(70);
            ordertable.getColumnModel().getColumn(1).setPreferredWidth(70);
            ordertable.getColumnModel().getColumn(2).setMinWidth(70);
            ordertable.getColumnModel().getColumn(2).setPreferredWidth(70);
            ordertable.getColumnModel().getColumn(3).setMinWidth(30);
            ordertable.getColumnModel().getColumn(3).setPreferredWidth(30);
            ordertable.getColumnModel().getColumn(4).setMinWidth(50);
            ordertable.getColumnModel().getColumn(4).setPreferredWidth(50);
            ordertable.getColumnModel().getColumn(5).setMinWidth(50);
            ordertable.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 102, 102));
        jTextField6.setText("                              Update Order");
        jTextField6.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        upop.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255)));
        upop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upopActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 153, 0));
        jLabel14.setText("Product Title");

        upopi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255)));
        upopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upopiActionPerformed(evt);
            }
        });

        updateorder.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        updateorder.setText("UPDATE");
        updateorder.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        updateorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateorderMouseClicked(evt);
            }
        });

        upoid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255)));
        upoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upoidActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("id");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 153, 0));
        jLabel16.setText("Categories");

        updatedate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 255, 255), null, null));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 153, 0));
        jLabel17.setText("Date");

        upoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Drinks", "Vitamins" }));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 153, 0));
        jLabel18.setText("Pieces");

        upprice.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255)));
        upprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uppriceActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 153, 0));
        jLabel20.setText("Price");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updatedate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upop, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upoid, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upopi)
                            .addComponent(upoc, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upprice, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateorder, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(upoid, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(upop, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(upoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(upopi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upprice, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updatedate, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateorder, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 102, 102));
        jTextField4.setText("                                            Delete Order ");
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        delo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255), new java.awt.Color(0, 102, 102), new java.awt.Color(102, 255, 255)));
        delo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deloActionPerformed(evt);
            }
        });

        deleteorder.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        deleteorder.setText("DELETE");
        deleteorder.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 1, 3, 1, new java.awt.Color(0, 102, 102)));
        deleteorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteorderMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("id");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(delo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteorder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteorder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hoverr.setBackground(new java.awt.Color(0, 102, 51));
        hoverr.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 153), new java.awt.Color(0, 51, 51), null, null));
        hoverr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hoverrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hoverrMouseExited(evt);
            }
        });

        availablezesb.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        availablezesb.setForeground(new java.awt.Color(255, 153, 0));
        availablezesb.setText("Zesto");
        availablezesb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availablezesbMouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 153, 51));
        jLabel27.setText("Available Stocks:");

        availableyakultb.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        availableyakultb.setForeground(new java.awt.Color(255, 153, 0));
        availableyakultb.setText("Yakult");
        availableyakultb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availableyakultbMouseClicked(evt);
            }
        });

        availableyakult.setBackground(new java.awt.Color(255, 255, 255));
        availableyakult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        availableyakult.setForeground(new java.awt.Color(255, 255, 255));
        availableyakult.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), null));

        availableenervonb.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        availableenervonb.setForeground(new java.awt.Color(255, 153, 0));
        availableenervonb.setText("Enervon");
        availableenervonb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availableenervonbMouseClicked(evt);
            }
        });

        availableenervon.setBackground(new java.awt.Color(255, 255, 255));
        availableenervon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        availableenervon.setForeground(new java.awt.Color(255, 255, 255));
        availableenervon.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), null));

        avalaiblepederin.setBackground(new java.awt.Color(255, 255, 255));
        avalaiblepederin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        avalaiblepederin.setForeground(new java.awt.Color(255, 255, 255));
        avalaiblepederin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), null));

        availablepederinb.setFont(new java.awt.Font("Euphemia", 1, 14)); // NOI18N
        availablepederinb.setForeground(new java.awt.Color(255, 153, 0));
        availablepederinb.setText("Periden-C");
        availablepederinb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                availablepederinbMouseClicked(evt);
            }
        });

        availablezes.setBackground(new java.awt.Color(255, 255, 255));
        availablezes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        availablezes.setForeground(new java.awt.Color(255, 255, 255));
        availablezes.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 51), null));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("10.00");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("15.00");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("27.00");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("15.00");

        javax.swing.GroupLayout hoverrLayout = new javax.swing.GroupLayout(hoverr);
        hoverr.setLayout(hoverrLayout);
        hoverrLayout.setHorizontalGroup(
            hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoverrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoverrLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoverrLayout.createSequentialGroup()
                        .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hoverrLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(availablezes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(availableyakult, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(hoverrLayout.createSequentialGroup()
                                .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availablezesb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hoverrLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11))
                                    .addComponent(availableyakultb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(2, 2, 2)
                        .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, hoverrLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(availableenervon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(avalaiblepederin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, hoverrLayout.createSequentialGroup()
                                .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableenervonb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(hoverrLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel12)))
                                .addGap(1, 1, 1)
                                .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hoverrLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel19)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(hoverrLayout.createSequentialGroup()
                                        .addComponent(availablepederinb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())))))))
        );
        hoverrLayout.setVerticalGroup(
            hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoverrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hoverrLayout.createSequentialGroup()
                        .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(availableyakult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(availablezes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(availableenervon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hoverrLayout.createSequentialGroup()
                                .addComponent(availablezesb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel19)))
                            .addGroup(hoverrLayout.createSequentialGroup()
                                .addGroup(hoverrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availablepederinb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(availableyakultb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(availableenervonb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(avalaiblepederin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/okayor.png"))); // NOI18N

        totalorder.setBackground(new java.awt.Color(0, 153, 51));
        totalorder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalorder.setForeground(new java.awt.Color(255, 255, 255));
        totalorder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 3));

        order.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        order.setForeground(new java.awt.Color(255, 102, 0));
        order.setText("Total Order:");
        order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(order)
                        .addGap(18, 18, 18)
                        .addComponent(totalorder, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hoverr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(order)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(totalorder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(hoverr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jLabel21.setFont(new java.awt.Font("Ink Free", 1, 30)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 51));
        jLabel21.setText("MANAGE YOUR DATA PRIVACY AND SECURITY");

        logoutb.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        logoutb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/logout2.png"))); // NOI18N
        logoutb.setText("Logout");
        logoutb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moya_javaproject/moya.images/administrator.png"))); // NOI18N

        nameuser2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nameuser2.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel21)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel25)
                        .addGap(18, 18, 18)
                        .addComponent(nameuser2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logoutb))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutb)
                    .addComponent(jLabel25)
                    .addComponent(jLabel21)
                    .addComponent(nameuser2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(471, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        landing welcome = new landing();
        welcome.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void manageGroupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageGroupsMouseClicked
        dispose();
        ManageGroups open = new ManageGroups();
        open.setVisible(true);
    }//GEN-LAST:event_manageGroupsMouseClicked

    private void manageGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageGroupsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageGroupsActionPerformed

    private void manageUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUsersMouseClicked
        dispose();
        ManageUsers open = new  ManageUsers();
        open.setVisible(true);
    }//GEN-LAST:event_manageUsersMouseClicked

    private void manageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageUsersActionPerformed

    private void manageProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageProductMouseClicked
        dispose();
        ManageProduct open = new  ManageProduct();
        open.setVisible(true);
    }//GEN-LAST:event_manageProductMouseClicked

    private void manageProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageProductActionPerformed

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        dispose();
        landing welcome = new landing();
        welcome.setVisible(true);
    }//GEN-LAST:event_dashboardMouseClicked

    private void dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardActionPerformed

    private void purchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purchaseMouseClicked
        dispose();
        ManageOrder welcome = new ManageOrder();
        welcome.setVisible(true);
    }//GEN-LAST:event_purchaseMouseClicked

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_purchaseActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void deloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deloActionPerformed

    private void deleteorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteorderMouseClicked
     orderdelete();
    }//GEN-LAST:event_deleteorderMouseClicked
private void orderdelete(){
       try
        {  
            Class.forName("com.mysql.jdbc.Driver");  
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaInventory","root","");  
            Statement stmt = con.createStatement();              
             
            String query = "DELETE FROM  `productorder` WHERE id = "+this.delo.getText()+"";
            stmt.execute(query);
            con.close();  
            new ManageOrder().setVisible(true);
            this.setVisible(false);
        
            JOptionPane.showMessageDialog(null,"Order is successfully deleted.","Alert",JOptionPane.WARNING_MESSAGE);    
        }
        catch(Exception e)
        {
            System.out.println(e);
        }  
}
    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void upopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upopActionPerformed

    private void upopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upopiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upopiActionPerformed

    private void updateorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateorderMouseClicked
       update();
    }//GEN-LAST:event_updateorderMouseClicked

    private void upoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upoidActionPerformed
    private void update(){
            try
        {  
            Class.forName("com.mysql.jdbc.Driver");  
            //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/employeevic","root","");  
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaInventory","root","");  
            Statement stmt = con.createStatement();              
             
            String query = "UPDATE `productorder` SET product_title='"+this.upop.getText()+"',category='"+this.upoc.getSelectedItem()+"',pieces='"+this.upopi.getText()+"',price='"+this.upprice.getText()+"',date='"+this.updatedate.getDate()+"' WHERE id='"+this.upoid.getText()+"'";
            stmt.execute(query);
            con.close();  
            new ManageOrder().setVisible(true);
            this.setVisible(false);
            JOptionPane.showMessageDialog(null,"Order is successfully updated.","Alert",JOptionPane.INFORMATION_MESSAGE);    
        }
        catch(Exception e)
        {
            System.out.println(e);
        }  
    }
    private void logoutbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbMouseClicked
        dispose();
        login welcome = new login();
        welcome.setVisible(true);
    }//GEN-LAST:event_logoutbMouseClicked

    private void addpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addpActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void addorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addorderMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver"); //load the driver
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javaInventory","root","");   //establishes the connection
            Statement stmt = (Statement) con.createStatement();
            Float total = Float.parseFloat(addp.getText())*Float.parseFloat(addprice.getText());
            String query = "INSERT INTO `productorder` ( `product_title`,`category`,`pieces`,`price`,`total`,`date`) VALUES ('"+addo.getText()+"','"+oc.getSelectedItem()+"','"+addp.getText()+"','"+addprice.getText()+"','"+total+"','"+dateo.getDate()+"')";     // Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Order is successfully added.");
            new ManageOrder().setVisible(true);
            this.setVisible(false);
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }
    }//GEN-LAST:event_addorderMouseClicked

    private void addoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addoActionPerformed

    private void availablezesbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availablezesbMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver"); //load the driver
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
            Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)
            ResultSet datas = stmt.executeQuery("select * from `products`");
            datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products` WHERE product_title ='Zesto'");
            datas.next();
            int count = datas.getInt(1);
            ResultSet order = stmt.executeQuery("select * from `productorder`");
            order = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE product_title ='Zesto'");//sum of the ordered p
            order.next();
            int count3 = order.getInt(1);
            availablezes.setText(String.valueOf(count-count3));//getting the final stocks

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);

        }
    }//GEN-LAST:event_availablezesbMouseClicked

    private void availableyakultbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableyakultbMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver"); //load the driver
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
            Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)
            ResultSet datas = stmt.executeQuery("select * from `products`");
            datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products` WHERE product_title ='Yakult'");
            datas.next();
            int count = datas.getInt(1);
            ResultSet order = stmt.executeQuery("select * from `productorder`");
            order = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE product_title ='Yakult'");//sum of the ordered p
            order.next();
            int count3 = order.getInt(1);
            availableyakult.setText(String.valueOf(count-count3));//get the final stock minus by the order

           

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);

        }
    }//GEN-LAST:event_availableyakultbMouseClicked

    private void availableenervonbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availableenervonbMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver"); //load the driver
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
            Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)
            ResultSet datas = stmt.executeQuery("select * from `products`");
            datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products` WHERE product_title ='Enervon'");
            datas.next();
            int count = datas.getInt(1);
            ResultSet order = stmt.executeQuery("select * from `productorder`");
            order = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE product_title ='Enervon'");
            order.next();
            int count3 = order.getInt(1);
            availableenervon.setText(String.valueOf(count-count3));//getting the final stocks

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
    }//GEN-LAST:event_availableenervonbMouseClicked

    private void availablepederinbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_availablepederinbMouseClicked
        try {
            Class.forName("com.mysql.jdbc.Driver"); //load the driver
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
            Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)
            ResultSet datas = stmt.executeQuery("select * from `products`");
            datas = stmt.executeQuery("SELECT SUM(`in_stock`)FROM `products` WHERE product_title ='Peridin-C'");//sum of  the stock in product t
            datas.next();
            int count = datas.getInt(1);
            ResultSet order = stmt.executeQuery("select * from `productorder`");
            order = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder` WHERE product_title ='Peridin-C'");//sum of the ordered p
            order.next();
            int count3 = order.getInt(1);
            avalaiblepederin.setText(String.valueOf(count-count3));//getting the final stocks minus with the orders

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
    }//GEN-LAST:event_availablepederinbMouseClicked
      public void setColor(JPanel p){
        p.setBackground(new Color(204,255,204));
    }
     public void resetColor(JPanel p1){
        p1.setBackground(new Color(0,102,51));
    }
    
    private void hoverrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverrMouseEntered
        setColor(hoverr);
    }//GEN-LAST:event_hoverrMouseEntered

    private void hoverrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hoverrMouseExited
          resetColor(hoverr);
    }//GEN-LAST:event_hoverrMouseExited

    private void ordertableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ordertableMouseClicked
        DefaultTableModel model = (DefaultTableModel) ordertable.getModel();
        int selectedIndex = ordertable.getSelectedRow();
         
        upoid.setText(model.getValueAt(selectedIndex, 0).toString());
        delo.setText(model.getValueAt(selectedIndex, 0).toString());
        upop.setText(model.getValueAt(selectedIndex, 1).toString());
        upoc.setSelectedItem(model.getValueAt(selectedIndex, 2).toString());
        upopi.setText(model.getValueAt(selectedIndex, 3).toString());
        upprice.setText(model.getValueAt(selectedIndex, 4).toString());
        
        
        
       
       
      
        
    }//GEN-LAST:event_ordertableMouseClicked

    private void addpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addpriceActionPerformed

    private void uppriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uppriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uppriceActionPerformed

    private void orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderMouseClicked
         try {
            Class.forName("com.mysql.jdbc.Driver"); //load the driver
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory", "root", ""); //establishes the connection
            Statement stmt = (Statement) con.createStatement(); //get the connection stream(connection port)
            ResultSet datas = stmt.executeQuery("select * from `productorder`");
            datas = stmt.executeQuery("SELECT SUM(`pieces`)FROM `productorder`");
            datas.next();
            int count3 = datas.getInt(1);
            totalorder.setText(String.valueOf(count3));//getting the final stocks

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
       
    }        
    }//GEN-LAST:event_orderMouseClicked
   public void getData(){
      int count = 0;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javainventory","root","");  
            Statement stmt = con.createStatement();

            ResultSet datas = stmt.executeQuery("select id,product_title,category,pieces,price,pieces*price as total,date from `productorder`");
            DefaultTableModel model = (DefaultTableModel) ordertable.getModel();
            while (datas.next()) {
                count = 1;
                model.addRow(new Object[]{datas.getInt("id"),datas.getString("product_title"),datas.getString("category"),datas.getInt("pieces"),datas.getString("price"),datas.getString("total"), datas.getString("date")});
            }
            if (count == 0) {
                JOptionPane.showMessageDialog(null, "No data found!.", "Alert", JOptionPane.WARNING_MESSAGE);
            }
            con.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addo;
    private javax.swing.JToggleButton addorder;
    private javax.swing.JTextField addp;
    private javax.swing.JTextField addprice;
    private javax.swing.JLabel availableenervon;
    private java.awt.Label availableenervonb;
    private java.awt.Label availablepederinb;
    private javax.swing.JLabel availableyakult;
    private java.awt.Label availableyakultb;
    private javax.swing.JLabel availablezes;
    private java.awt.Label availablezesb;
    private javax.swing.JLabel avalaiblepederin;
    private javax.swing.JToggleButton dashboard;
    private com.toedter.calendar.JDateChooser dateo;
    private javax.swing.JToggleButton deleteorder;
    private javax.swing.JTextField delo;
    private javax.swing.JPanel hoverr;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel logoutb;
    private javax.swing.JToggleButton manageGroups;
    private javax.swing.JToggleButton manageProduct;
    private javax.swing.JToggleButton manageUsers;
    private javax.swing.JLabel nameuser2;
    private javax.swing.JComboBox<String> oc;
    private javax.swing.JLabel order;
    private javax.swing.JTable ordertable;
    private javax.swing.JToggleButton purchase;
    private javax.swing.JLabel totalorder;
    private com.toedter.calendar.JDateChooser updatedate;
    private javax.swing.JToggleButton updateorder;
    private javax.swing.JComboBox<String> upoc;
    private javax.swing.JTextField upoid;
    private javax.swing.JTextField upop;
    private javax.swing.JTextField upopi;
    private javax.swing.JTextField upprice;
    // End of variables declaration//GEN-END:variables
}
